### ISSUE TITLE
add usage example to wiki

### ISSUE THREAD

**Issue by kamilsk** [octolab/Cleaner#24]
https://github.com/octolab/Cleaner/tree/master/tests/integration

**Comment by mlocati** [comment]
What about also suggesting a list of categories in https://github.com/octolab/Cleaner/wiki ?
That way, package maintainers are invited to use a common set of category names.

**Comment by kamilsk** [comment]
could you provide this list with description?

**Comment by mlocati** [comment]
- `doc`  
  Documentations, manual, readme... (licenses are excluded since they should always stay with the packages)
- `example`  
  Examples, tutorials, ...
- `test`  
  Test-related files
- `bin`  
  Command-line related files (for instance, if a project uses Doctrine DBAL only as a library, the [`bin`](https://github.com/doctrine/dbal/tree/v2.4.5/bin) folder is not needed)

**Comment by kamilsk** [comment]
fixed https://github.com/octolab/Cleaner/wiki#recommended-categories

**Comment by kamilsk** [comment]
fixed https://github.com/octolab/Cleaner/wiki#integration-test
